#!/bin/sh
echo "Checking for .only() calls..."
egrep -irn --color "(describe|it)\.only" "$(pwd)/src"
if [ "$?" -eq "1" ]
then
    echo "nothing found, success..."
    exit 0
fi

echo "Found one or more .only() calls!"
exit 1
