cinst git
cinst gitextensions
cinst githubforwindows
cinst curl
cinst beyondcompare
cinst meld
cinst sublimetext3.app
cinst googledrive
cinst filezilla
cinst fiddler4
cinst nuget.commandline
cinst nugetpackageexplorer
cinst poshgit
cinst phantomjs
cinst cyg-get
cinst dotpeek
cinst expresso
cinst rdcman
cinst linqpad
cinst galliobundle
cinst debugview
