#!/bin/bash
#
# Prepend the story ID and description (as parsed from the current branch name)
# to the commit message.
#

MESSAGE_FILE="$1"
BRANCH_CURRENT="$(git rev-parse --abbrev-ref HEAD)"
BRANCH_REGEX='^[[:digit:]]+'
STORY_ID="$(echo $BRANCH_CURRENT | egrep -o $BRANCH_REGEX)"

if [[ -z $STORY_ID ]]; then
    # Couldn't figure out what story this is. Warn the user, but continue
    echo "Warning: unable to determine story number from branch name" >&2
else
    # Prepend the story ID to the message file. OSX ships with a crazy (old)
    # version of sed, so newline characters must be converted rather than
    # interpolated.
    sed -i '' '1i\'$'\n'"$STORY_ID " $MESSAGE_FILE
fi
